#!/bin/bash
rm /tmp/screenshotblur.png
rm /tmp/screenshot.png
scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
loginctl suspend
betterlockscreen -l pixel -u /tmp/screenshotblur.png
